Feature clean up shooter code
Decatur-Robotics/FRC-2024-Team-4026 pull request #55
Opened 2024-01-25 21:06 UTC by Tr01ler

):

2024-01-25 21:15 UTC, Tr01ler commented
I don't know what's happening, but I haven't even made any changes yet.

2024-01-27 15:34 UTC, Beckoe commented
Everything looks good, but we need a change now. Please run the shooter motors separately (so one doesn't follow the other) and make one side run at a slightly lower speed. Use the faster side in getShooterMotorPower(). Also, move all values to a constants file (voltage, motor speeds, etc.).

2024-01-27 18:26 UTC, renatodellosso requested changes

2024-01-27 18:26 UTC, renatodellosso commented on RobotCode/src/main/java/frc/robot/subsystems/ShooterSubsystem.java
>  		ShooterMotorMain.enableVoltageCompensation(VOLTAGE);
Voltage comp is done by default now, you don't need to do it here

2024-01-27 18:26 UTC, renatodellosso commented on RobotCode/src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +	 * @param power
Remove the @param parameter name if you haven't added any detail to it

2024-01-27 18:35 UTC, renatodellosso requested changes

2024-01-27 18:35 UTC, renatodellosso commented on RobotCode/src/main/java/frc/robot/subsystems/ShooterSubsystem.java
> +		ShooterMotorSub.set(newShooterPower * 0.8);
Make the 0.8 a constant

2024-01-27 18:40 UTC, renatodellosso approved these changes
Great work!

2024-01-27 18:40 UTC, merged