Logger implementation
Decatur-Robotics/FRC-2024-Team-4026 pull request #78
Opened 2024-02-04 19:39 UTC by li46554

Added logger to classes

2024-02-04 20:22 UTC, Henrytoo requested changes
The levels for the logging messages are not the correct levels. Check the documentation for Logging so that you know which ones should be used. In addition, these logs need to be more specific and self-descriptive of what they are for, You will need to check old code to know how to format these new logs.

2024-02-05 21:16 UTC, PPenguin1 commented on RobotCode/src/main/java/frc/robot/commands/ClimberCommand.java
This is not needed

2024-02-05 21:36 UTC, PPenguin1 approved these changes

2024-02-05 22:02 UTC, Henrytoo requested changes
Again these logs need to be more specific so that we can know exactly where the problem is without any confusion.

2024-02-06 22:15 UTC, seankid approved these changes
mucho bueno alberto. es muy brazo.

2024-02-19 21:24 UTC, closed without merging